// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Config, Options, TDataShape } from './types.gen'

let _config: Config

export const createConfig = (overrides?: Partial<Config>): Config => ({
  baseUrl: '/api/v1',
  ...overrides,
})

export const createClient = (config: Config = createConfig()): Client => {
  _config = config

  const request = async <TData extends TDataShape = TDataShape, TError = unknown, ThrowOnError extends boolean = false>(
    opts: Options<TData, ThrowOnError>
  ): Promise<any> => {
    let url = `${config.baseUrl}${opts.url}`
    if (opts.path) {
      for (const [key, value] of Object.entries(opts.path as Record<string, unknown>)) {
        url = url.replace(`{${key}}`, String(value))
      }
    }
    const query = opts.query
    const queryString = query ? '?' + new URLSearchParams(
      Object.entries(query).filter(([, v]) => v !== undefined && v !== null).map(([k, v]) => [k, String(v)])
    ).toString() : ''

    const res = await fetch(`${url}${queryString}`, {
      method: opts.method?.toUpperCase() || 'GET',
      headers: opts.headers as HeadersInit,
      body: opts.body ? JSON.stringify(opts.body) : undefined,
    })

    if (!res.ok) {
      const error = await res.text().catch(() => 'Unknown error')
      const err = new Error(error || `Request failed with status ${res.status}`)
      if (opts.throwOnError !== false) throw err
      return { error: err }
    }

    if (res.status === 204) return { data: undefined }
    const data = await res.json()
    return { data }
  }

  const client: Client = {
    get: <TData extends TDataShape = TDataShape>(opts: any) => request<TData>({ ...opts, method: 'get' }),
    post: <TData extends TDataShape = TDataShape>(opts: any) => request<TData>({ ...opts, method: 'post' }),
    put: <TData extends TDataShape = TDataShape>(opts: any) => request<TData>({ ...opts, method: 'put' }),
    delete: <TData extends TDataShape = TDataShape>(opts: any) => request<TData>({ ...opts, method: 'delete' }),
  }

  Object.defineProperty(client, 'getConfig', { value: () => _config })
  return client
}

export const client = createClient()
export const { get, head, options, patch, post, put, del } = client
