// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateCategoryData, CreateCategoryErrors, CreateCategoryResponses, CreateEventData, CreateEventErrors, CreateEventResponses, CreatePetData, CreatePetErrors, CreatePetResponses, CreateTagData, CreateTagErrors, CreateTagResponses, CreateTaskData, CreateTaskErrors, CreateTaskResponses, CurrentUserData, CurrentUserErrors, CurrentUserResponses, DeleteCategoryData, DeleteCategoryErrors, DeleteCategoryResponses, DeleteEventData, DeleteEventErrors, DeleteEventResponses, DeleteTagData, DeleteTagErrors, DeleteTagResponses, DeleteTaskData, DeleteTaskErrors, DeleteTaskResponses, GetEventByIdData, GetEventByIdErrors, GetEventByIdResponses, GetMyPetData, GetMyPetErrors, GetMyPetResponses, GetShopItemsData, GetShopItemsResponses, GrantPetRewardData, GrantPetRewardErrors, GrantPetRewardResponses, InteractWithPetData, InteractWithPetErrors, InteractWithPetResponses, ListCategoriesData, ListCategoriesErrors, ListCategoriesResponses, ListEventsData, ListEventsErrors, ListEventsResponses, ListTagsData, ListTagsErrors, ListTagsResponses, ListTasksData, ListTasksErrors, ListTasksResponses, LoginData, LoginErrors, LoginResponses, LogoutData, LogoutErrors, LogoutResponses, MoveTaskData, MoveTaskErrors, MoveTaskResponses, PurchaseItemData, PurchaseItemErrors, PurchaseItemResponses, RefreshTokenData, RefreshTokenErrors, RefreshTokenResponses, RegisterData, RegisterErrors, RegisterResponses, SubscribeNotificationsData, SubscribeNotificationsErrors, SubscribeNotificationsResponse, SubscribeNotificationsResponses, UnequipAccessoryData, UnequipAccessoryErrors, UnequipAccessoryResponses, UpdateCategoryData, UpdateCategoryErrors, UpdateCategoryResponses, UpdateEventData, UpdateEventErrors, UpdateEventResponses, UpdatePetData, UpdatePetErrors, UpdatePetResponses, UpdateTagData, UpdateTagErrors, UpdateTagResponses, UpdateTaskData, UpdateTaskErrors, UpdateTaskResponses, WechatLoginData, WechatLoginErrors, WechatLoginResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * 注册新用户（自动登录）
 */
export const register = <ThrowOnError extends boolean = false>(options: Options<RegisterData, ThrowOnError>) => (options.client ?? client).post<RegisterResponses, RegisterErrors, ThrowOnError>({
    url: '/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 登录获取 token
 */
export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>) => (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 微信小程序登录（wx.login code 换 JWT，未注册自动开户）
 */
export const wechatLogin = <ThrowOnError extends boolean = false>(options: Options<WechatLoginData, ThrowOnError>) => (options.client ?? client).post<WechatLoginResponses, WechatLoginErrors, ThrowOnError>({
    url: '/auth/wechat-login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 使用 refresh token 换取新 access token
 */
export const refreshToken = <ThrowOnError extends boolean = false>(options: Options<RefreshTokenData, ThrowOnError>) => (options.client ?? client).post<RefreshTokenResponses, RefreshTokenErrors, ThrowOnError>({
    url: '/auth/refresh',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 注销当前会话（清除 SSE Cookie）
 */
export const logout = <ThrowOnError extends boolean = false>(options?: Options<LogoutData, ThrowOnError>) => (options?.client ?? client).post<LogoutResponses, LogoutErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/logout',
    ...options
});

/**
 * 获取当前登录用户信息
 */
export const currentUser = <ThrowOnError extends boolean = false>(options?: Options<CurrentUserData, ThrowOnError>) => (options?.client ?? client).get<CurrentUserResponses, CurrentUserErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/me',
    ...options
});

/**
 * 按时间范围查询日程
 */
export const listEvents = <ThrowOnError extends boolean = false>(options: Options<ListEventsData, ThrowOnError>) => (options.client ?? client).get<ListEventsResponses, ListEventsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/events',
    ...options
});

/**
 * 创建日程
 */
export const createEvent = <ThrowOnError extends boolean = false>(options: Options<CreateEventData, ThrowOnError>) => (options.client ?? client).post<CreateEventResponses, CreateEventErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/events',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 删除日程
 */
export const deleteEvent = <ThrowOnError extends boolean = false>(options: Options<DeleteEventData, ThrowOnError>) => (options.client ?? client).delete<DeleteEventResponses, DeleteEventErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/events/{id}',
    ...options
});

/**
 * 查询单个日程
 */
export const getEventById = <ThrowOnError extends boolean = false>(options: Options<GetEventByIdData, ThrowOnError>) => (options.client ?? client).get<GetEventByIdResponses, GetEventByIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/events/{id}',
    ...options
});

/**
 * 更新日程
 */
export const updateEvent = <ThrowOnError extends boolean = false>(options: Options<UpdateEventData, ThrowOnError>) => (options.client ?? client).put<UpdateEventResponses, UpdateEventErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/events/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 获取当前用户的所有分类
 */
export const listCategories = <ThrowOnError extends boolean = false>(options?: Options<ListCategoriesData, ThrowOnError>) => (options?.client ?? client).get<ListCategoriesResponses, ListCategoriesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/categories',
    ...options
});

/**
 * 创建分类
 */
export const createCategory = <ThrowOnError extends boolean = false>(options: Options<CreateCategoryData, ThrowOnError>) => (options.client ?? client).post<CreateCategoryResponses, CreateCategoryErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/categories',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 删除分类
 */
export const deleteCategory = <ThrowOnError extends boolean = false>(options: Options<DeleteCategoryData, ThrowOnError>) => (options.client ?? client).delete<DeleteCategoryResponses, DeleteCategoryErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/categories/{id}',
    ...options
});

/**
 * 更新分类
 */
export const updateCategory = <ThrowOnError extends boolean = false>(options: Options<UpdateCategoryData, ThrowOnError>) => (options.client ?? client).put<UpdateCategoryResponses, UpdateCategoryErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/categories/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 获取当前用户的所有标签
 */
export const listTags = <ThrowOnError extends boolean = false>(options?: Options<ListTagsData, ThrowOnError>) => (options?.client ?? client).get<ListTagsResponses, ListTagsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tags',
    ...options
});

/**
 * 创建标签
 */
export const createTag = <ThrowOnError extends boolean = false>(options: Options<CreateTagData, ThrowOnError>) => (options.client ?? client).post<CreateTagResponses, CreateTagErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tags',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 删除标签
 */
export const deleteTag = <ThrowOnError extends boolean = false>(options: Options<DeleteTagData, ThrowOnError>) => (options.client ?? client).delete<DeleteTagResponses, DeleteTagErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tags/{id}',
    ...options
});

/**
 * 更新标签
 */
export const updateTag = <ThrowOnError extends boolean = false>(options: Options<UpdateTagData, ThrowOnError>) => (options.client ?? client).put<UpdateTagResponses, UpdateTagErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tags/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 获取当前用户的宠物详情
 */
export const getMyPet = <ThrowOnError extends boolean = false>(options?: Options<GetMyPetData, ThrowOnError>) => (options?.client ?? client).get<GetMyPetResponses, GetMyPetErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/pets/me',
    ...options
});

/**
 * 创建当前用户的宠物
 */
export const createPet = <ThrowOnError extends boolean = false>(options: Options<CreatePetData, ThrowOnError>) => (options.client ?? client).post<CreatePetResponses, CreatePetErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/pets/me',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 更新宠物（仅支持改名）
 */
export const updatePet = <ThrowOnError extends boolean = false>(options: Options<UpdatePetData, ThrowOnError>) => (options.client ?? client).put<UpdatePetResponses, UpdatePetErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/pets/me',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 与宠物互动（喂食/玩耍）
 */
export const interactWithPet = <ThrowOnError extends boolean = false>(options: Options<InteractWithPetData, ThrowOnError>) => (options.client ?? client).post<InteractWithPetResponses, InteractWithPetErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/pets/me/interact',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 取下当前配饰（幂等，未装备时同样成功）
 */
export const unequipAccessory = <ThrowOnError extends boolean = false>(options?: Options<UnequipAccessoryData, ThrowOnError>) => (options?.client ?? client).delete<UnequipAccessoryResponses, UnequipAccessoryErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/pets/me/accessory',
    ...options
});

/**
 * 领取行为奖励（幂等，granted=false 表示未发放）
 */
export const grantPetReward = <ThrowOnError extends boolean = false>(options: Options<GrantPetRewardData, ThrowOnError>) => (options.client ?? client).post<GrantPetRewardResponses, GrantPetRewardErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/pets/me/rewards',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 获取商店物品列表
 */
export const getShopItems = <ThrowOnError extends boolean = false>(options?: Options<GetShopItemsData, ThrowOnError>) => (options?.client ?? client).get<GetShopItemsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/shop/items',
    ...options
});

/**
 * 购买物品（即时消费模式）
 */
export const purchaseItem = <ThrowOnError extends boolean = false>(options: Options<PurchaseItemData, ThrowOnError>) => (options.client ?? client).post<PurchaseItemResponses, PurchaseItemErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/shop/purchase',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 查询任务列表
 */
export const listTasks = <ThrowOnError extends boolean = false>(options?: Options<ListTasksData, ThrowOnError>) => (options?.client ?? client).get<ListTasksResponses, ListTasksErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tasks',
    ...options
});

/**
 * 创建任务
 */
export const createTask = <ThrowOnError extends boolean = false>(options: Options<CreateTaskData, ThrowOnError>) => (options.client ?? client).post<CreateTaskResponses, CreateTaskErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tasks',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 删除任务
 */
export const deleteTask = <ThrowOnError extends boolean = false>(options: Options<DeleteTaskData, ThrowOnError>) => (options.client ?? client).delete<DeleteTaskResponses, DeleteTaskErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tasks/{id}',
    ...options
});

/**
 * 更新任务
 */
export const updateTask = <ThrowOnError extends boolean = false>(options: Options<UpdateTaskData, ThrowOnError>) => (options.client ?? client).put<UpdateTaskResponses, UpdateTaskErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tasks/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 移动任务到目标列
 */
export const moveTask = <ThrowOnError extends boolean = false>(options: Options<MoveTaskData, ThrowOnError>) => (options.client ?? client).patch<MoveTaskResponses, MoveTaskErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tasks/{id}/move',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 订阅实时通知（SSE）
 *
 * Server-Sent Events 长连接。**鉴权**：通过登录时下发的
 * `dsa_sse_session` HttpOnly Cookie（EventSource 不支持自定义 header，
 * 因此不复用 Authorization Bearer）。
 *
 * 服务端会推送以下命名事件：
 * - `connect`：连接建立成功，data 为字符串 `"connected"`。
 * - `reminder`：日程提醒，data 为 `ReminderEvent` JSON。
 * - `heartbeat`：心跳保活，data 为字符串 `"ping"`。
 *
 * 每条 reminder 仅推送给该 event 所属用户的连接。
 *
 */
export const subscribeNotifications = <ThrowOnError extends boolean = false>(options?: Options<SubscribeNotificationsData, ThrowOnError, SubscribeNotificationsResponse>) => (options?.client ?? client).sse.get<SubscribeNotificationsResponses, SubscribeNotificationsErrors, ThrowOnError>({ url: '/sse/notifications', ...options });
