// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateCategoryData, CreateCategoryErrors, CreateCategoryResponses, CreateEventData, CreateEventErrors, CreateEventResponses, CreateTagData, CreateTagErrors, CreateTagResponses, DeleteCategoryData, DeleteCategoryErrors, DeleteCategoryResponses, DeleteEventData, DeleteEventErrors, DeleteEventResponses, DeleteTagData, DeleteTagErrors, DeleteTagResponses, GetEventByIdData, GetEventByIdErrors, GetEventByIdResponses, ListCategoriesData, ListCategoriesResponses, ListEventsData, ListEventsErrors, ListEventsResponses, ListTagsData, ListTagsResponses, SubscribeNotificationsData, SubscribeNotificationsResponse, SubscribeNotificationsResponses, UpdateCategoryData, UpdateCategoryErrors, UpdateCategoryResponses, UpdateEventData, UpdateEventErrors, UpdateEventResponses, UpdateTagData, UpdateTagErrors, UpdateTagResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * 按时间范围查询日程
 */
export const listEvents = <ThrowOnError extends boolean = false>(options: Options<ListEventsData, ThrowOnError>) => (options.client ?? client).get<ListEventsResponses, ListEventsErrors, ThrowOnError>({ url: '/events', ...options });

/**
 * 创建日程
 */
export const createEvent = <ThrowOnError extends boolean = false>(options: Options<CreateEventData, ThrowOnError>) => (options.client ?? client).post<CreateEventResponses, CreateEventErrors, ThrowOnError>({
    url: '/events',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 删除日程
 */
export const deleteEvent = <ThrowOnError extends boolean = false>(options: Options<DeleteEventData, ThrowOnError>) => (options.client ?? client).delete<DeleteEventResponses, DeleteEventErrors, ThrowOnError>({ url: '/events/{id}', ...options });

/**
 * 查询单个日程
 */
export const getEventById = <ThrowOnError extends boolean = false>(options: Options<GetEventByIdData, ThrowOnError>) => (options.client ?? client).get<GetEventByIdResponses, GetEventByIdErrors, ThrowOnError>({ url: '/events/{id}', ...options });

/**
 * 更新日程
 */
export const updateEvent = <ThrowOnError extends boolean = false>(options: Options<UpdateEventData, ThrowOnError>) => (options.client ?? client).put<UpdateEventResponses, UpdateEventErrors, ThrowOnError>({
    url: '/events/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 获取所有分类
 */
export const listCategories = <ThrowOnError extends boolean = false>(options?: Options<ListCategoriesData, ThrowOnError>) => (options?.client ?? client).get<ListCategoriesResponses, unknown, ThrowOnError>({ url: '/categories', ...options });

/**
 * 创建分类
 */
export const createCategory = <ThrowOnError extends boolean = false>(options: Options<CreateCategoryData, ThrowOnError>) => (options.client ?? client).post<CreateCategoryResponses, CreateCategoryErrors, ThrowOnError>({
    url: '/categories',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 删除分类
 */
export const deleteCategory = <ThrowOnError extends boolean = false>(options: Options<DeleteCategoryData, ThrowOnError>) => (options.client ?? client).delete<DeleteCategoryResponses, DeleteCategoryErrors, ThrowOnError>({ url: '/categories/{id}', ...options });

/**
 * 更新分类
 */
export const updateCategory = <ThrowOnError extends boolean = false>(options: Options<UpdateCategoryData, ThrowOnError>) => (options.client ?? client).put<UpdateCategoryResponses, UpdateCategoryErrors, ThrowOnError>({
    url: '/categories/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 获取所有标签
 */
export const listTags = <ThrowOnError extends boolean = false>(options?: Options<ListTagsData, ThrowOnError>) => (options?.client ?? client).get<ListTagsResponses, unknown, ThrowOnError>({ url: '/tags', ...options });

/**
 * 创建标签
 */
export const createTag = <ThrowOnError extends boolean = false>(options: Options<CreateTagData, ThrowOnError>) => (options.client ?? client).post<CreateTagResponses, CreateTagErrors, ThrowOnError>({
    url: '/tags',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 删除标签
 */
export const deleteTag = <ThrowOnError extends boolean = false>(options: Options<DeleteTagData, ThrowOnError>) => (options.client ?? client).delete<DeleteTagResponses, DeleteTagErrors, ThrowOnError>({ url: '/tags/{id}', ...options });

/**
 * 更新标签
 */
export const updateTag = <ThrowOnError extends boolean = false>(options: Options<UpdateTagData, ThrowOnError>) => (options.client ?? client).put<UpdateTagResponses, UpdateTagErrors, ThrowOnError>({
    url: '/tags/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 订阅实时通知（SSE）
 *
 * Server-Sent Events 长连接，服务端会推送以下命名事件：
 *
 * - `connect`：连接建立成功，data 为字符串 `"connected"`。
 * - `reminder`：日程提醒，data 为 `ReminderEvent` 的 JSON 序列化字符串。
 * - `heartbeat`：心跳保活，data 为字符串 `"ping"`。
 *
 * 前端应使用浏览器原生 `EventSource` 订阅，并通过 `addEventListener('reminder', handler)` 监听具体事件类型。
 *
 */
export const subscribeNotifications = <ThrowOnError extends boolean = false>(options?: Options<SubscribeNotificationsData, ThrowOnError, SubscribeNotificationsResponse>) => (options?.client ?? client).sse.get<SubscribeNotificationsResponses, unknown, ThrowOnError>({ url: '/sse/notifications', ...options });
