// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api/v1` | (string & {});
};

export type RegisterRequest = {
    username: string;
    email: string;
    password: string;
    displayName?: string;
};

export type LoginRequest = {
    usernameOrEmail: string;
    password: string;
};

export type RefreshRequest = {
    refreshToken: string;
};

export type LoginResponse = {
    accessToken: string;
    refreshToken: string;
    /**
     * access token 有效期（秒）
     */
    expiresIn: number;
    user: UserResponse;
};

export type UserResponse = {
    id?: number;
    username?: string;
    email?: string;
    displayName?: string;
    avatarUrl?: string;
    createdAt?: string;
};

export type EventCreateRequest = {
    title: string;
    description?: string;
    startTime: string;
    endTime: string;
    allDay?: boolean;
    location?: string;
    color?: string;
    reminderMinutes?: number;
    status?: EventStatus;
    categoryId?: number;
    tagIds?: Array<number>;
};

export type EventUpdateRequest = EventCreateRequest;

export type EventResponse = {
    id?: number;
    title?: string;
    description?: string;
    startTime?: string;
    endTime?: string;
    allDay?: boolean;
    location?: string;
    color?: string;
    reminderMinutes?: number;
    status?: EventStatus;
    categoryId?: number;
    categoryName?: string;
    categoryColor?: string;
    tags?: Array<TagResponse>;
    createdAt?: string;
    updatedAt?: string;
};

/**
 * 日程状态。PLANNED=计划中，COMPLETED=已完成，CANCELLED=已取消。
 * 创建时缺省按 PLANNED 处理（由服务端保障，不在 schema 声明 default，
 * 避免代码生成器把 default 套用到查询过滤参数上）。
 *
 */
export type EventStatus = 'PLANNED' | 'COMPLETED' | 'CANCELLED';

export type CategoryCreateRequest = {
    name: string;
    color?: string;
    description?: string;
};

export type CategoryResponse = {
    id?: number;
    name?: string;
    color?: string;
    description?: string;
};

export type TagCreateRequest = {
    name: string;
    color?: string;
};

export type TagResponse = {
    id?: number;
    name?: string;
    color?: string;
};

/**
 * SSE `reminder` 事件 data 的反序列化结构
 */
export type ReminderEvent = {
    id?: number;
    title?: string;
    startTime?: string;
    reminderMinutes?: number;
};

/**
 * 错误响应包装
 */
export type ApiResponse = {
    code?: number;
    message?: string;
};

export type RegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type RegisterErrors = {
    /**
     * 请求参数不合法
     */
    400: ApiResponse;
    /**
     * 资源冲突（用户名/邮箱/分类名/标签名重复）
     */
    409: ApiResponse;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    /**
     * 注册成功
     */
    201: LoginResponse;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginErrors = {
    /**
     * 请求参数不合法
     */
    400: ApiResponse;
    /**
     * 未认证或 token 失效
     */
    401: ApiResponse;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * 登录成功
     */
    200: LoginResponse;
};

export type LoginResponse2 = LoginResponses[keyof LoginResponses];

export type RefreshTokenData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type RefreshTokenErrors = {
    /**
     * 未认证或 token 失效
     */
    401: ApiResponse;
};

export type RefreshTokenError = RefreshTokenErrors[keyof RefreshTokenErrors];

export type RefreshTokenResponses = {
    /**
     * 续签成功
     */
    200: LoginResponse;
};

export type RefreshTokenResponse = RefreshTokenResponses[keyof RefreshTokenResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutErrors = {
    /**
     * 未认证或 token 失效
     */
    401: ApiResponse;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    /**
     * 注销成功
     */
    204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type CurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type CurrentUserErrors = {
    /**
     * 未认证或 token 失效
     */
    401: ApiResponse;
};

export type CurrentUserError = CurrentUserErrors[keyof CurrentUserErrors];

export type CurrentUserResponses = {
    /**
     * 成功
     */
    200: UserResponse;
};

export type CurrentUserResponse = CurrentUserResponses[keyof CurrentUserResponses];

export type ListEventsData = {
    body?: never;
    path?: never;
    query: {
        start: string;
        end: string;
        categoryId?: number;
        /**
         * 按标签过滤（事件含有该标签即命中）
         */
        tagId?: number;
        /**
         * 按状态过滤
         */
        status?: EventStatus;
        /**
         * 按标题、描述、地点搜索
         */
        keyword?: string;
        page?: number;
        size?: number;
    };
    url: '/events';
};

export type ListEventsErrors = {
    /**
     * 请求参数不合法
     */
    400: ApiResponse;
    /**
     * 未认证或 token 失效
     */
    401: ApiResponse;
};

export type ListEventsError = ListEventsErrors[keyof ListEventsErrors];

export type ListEventsResponses = {
    /**
     * 成功
     */
    200: Array<EventResponse>;
};

export type ListEventsResponse = ListEventsResponses[keyof ListEventsResponses];

export type CreateEventData = {
    body: EventCreateRequest;
    path?: never;
    query?: never;
    url: '/events';
};

export type CreateEventErrors = {
    /**
     * 请求参数不合法
     */
    400: ApiResponse;
    /**
     * 未认证或 token 失效
     */
    401: ApiResponse;
};

export type CreateEventError = CreateEventErrors[keyof CreateEventErrors];

export type CreateEventResponses = {
    /**
     * 创建成功
     */
    201: EventResponse;
};

export type CreateEventResponse = CreateEventResponses[keyof CreateEventResponses];

export type DeleteEventData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/events/{id}';
};

export type DeleteEventErrors = {
    /**
     * 未认证或 token 失效
     */
    401: ApiResponse;
    /**
     * 资源不存在或无权访问
     */
    404: ApiResponse;
};

export type DeleteEventError = DeleteEventErrors[keyof DeleteEventErrors];

export type DeleteEventResponses = {
    /**
     * 删除成功
     */
    204: void;
};

export type DeleteEventResponse = DeleteEventResponses[keyof DeleteEventResponses];

export type GetEventByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/events/{id}';
};

export type GetEventByIdErrors = {
    /**
     * 未认证或 token 失效
     */
    401: ApiResponse;
    /**
     * 资源不存在或无权访问
     */
    404: ApiResponse;
};

export type GetEventByIdError = GetEventByIdErrors[keyof GetEventByIdErrors];

export type GetEventByIdResponses = {
    /**
     * 成功
     */
    200: EventResponse;
};

export type GetEventByIdResponse = GetEventByIdResponses[keyof GetEventByIdResponses];

export type UpdateEventData = {
    body: EventUpdateRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/events/{id}';
};

export type UpdateEventErrors = {
    /**
     * 请求参数不合法
     */
    400: ApiResponse;
    /**
     * 未认证或 token 失效
     */
    401: ApiResponse;
    /**
     * 资源不存在或无权访问
     */
    404: ApiResponse;
};

export type UpdateEventError = UpdateEventErrors[keyof UpdateEventErrors];

export type UpdateEventResponses = {
    /**
     * 更新成功
     */
    200: EventResponse;
};

export type UpdateEventResponse = UpdateEventResponses[keyof UpdateEventResponses];

export type ListCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/categories';
};

export type ListCategoriesErrors = {
    /**
     * 未认证或 token 失效
     */
    401: ApiResponse;
};

export type ListCategoriesError = ListCategoriesErrors[keyof ListCategoriesErrors];

export type ListCategoriesResponses = {
    /**
     * 成功
     */
    200: Array<CategoryResponse>;
};

export type ListCategoriesResponse = ListCategoriesResponses[keyof ListCategoriesResponses];

export type CreateCategoryData = {
    body: CategoryCreateRequest;
    path?: never;
    query?: never;
    url: '/categories';
};

export type CreateCategoryErrors = {
    /**
     * 请求参数不合法
     */
    400: ApiResponse;
    /**
     * 未认证或 token 失效
     */
    401: ApiResponse;
    /**
     * 资源冲突（用户名/邮箱/分类名/标签名重复）
     */
    409: ApiResponse;
};

export type CreateCategoryError = CreateCategoryErrors[keyof CreateCategoryErrors];

export type CreateCategoryResponses = {
    /**
     * 创建成功
     */
    201: CategoryResponse;
};

export type CreateCategoryResponse = CreateCategoryResponses[keyof CreateCategoryResponses];

export type DeleteCategoryData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/categories/{id}';
};

export type DeleteCategoryErrors = {
    /**
     * 未认证或 token 失效
     */
    401: ApiResponse;
    /**
     * 资源不存在或无权访问
     */
    404: ApiResponse;
};

export type DeleteCategoryError = DeleteCategoryErrors[keyof DeleteCategoryErrors];

export type DeleteCategoryResponses = {
    /**
     * 删除成功
     */
    204: void;
};

export type DeleteCategoryResponse = DeleteCategoryResponses[keyof DeleteCategoryResponses];

export type UpdateCategoryData = {
    body: CategoryCreateRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/categories/{id}';
};

export type UpdateCategoryErrors = {
    /**
     * 未认证或 token 失效
     */
    401: ApiResponse;
    /**
     * 资源不存在或无权访问
     */
    404: ApiResponse;
    /**
     * 资源冲突（用户名/邮箱/分类名/标签名重复）
     */
    409: ApiResponse;
};

export type UpdateCategoryError = UpdateCategoryErrors[keyof UpdateCategoryErrors];

export type UpdateCategoryResponses = {
    /**
     * 更新成功
     */
    200: CategoryResponse;
};

export type UpdateCategoryResponse = UpdateCategoryResponses[keyof UpdateCategoryResponses];

export type ListTagsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tags';
};

export type ListTagsErrors = {
    /**
     * 未认证或 token 失效
     */
    401: ApiResponse;
};

export type ListTagsError = ListTagsErrors[keyof ListTagsErrors];

export type ListTagsResponses = {
    /**
     * 成功
     */
    200: Array<TagResponse>;
};

export type ListTagsResponse = ListTagsResponses[keyof ListTagsResponses];

export type CreateTagData = {
    body: TagCreateRequest;
    path?: never;
    query?: never;
    url: '/tags';
};

export type CreateTagErrors = {
    /**
     * 请求参数不合法
     */
    400: ApiResponse;
    /**
     * 未认证或 token 失效
     */
    401: ApiResponse;
    /**
     * 资源冲突（用户名/邮箱/分类名/标签名重复）
     */
    409: ApiResponse;
};

export type CreateTagError = CreateTagErrors[keyof CreateTagErrors];

export type CreateTagResponses = {
    /**
     * 创建成功
     */
    201: TagResponse;
};

export type CreateTagResponse = CreateTagResponses[keyof CreateTagResponses];

export type DeleteTagData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/tags/{id}';
};

export type DeleteTagErrors = {
    /**
     * 未认证或 token 失效
     */
    401: ApiResponse;
    /**
     * 资源不存在或无权访问
     */
    404: ApiResponse;
};

export type DeleteTagError = DeleteTagErrors[keyof DeleteTagErrors];

export type DeleteTagResponses = {
    /**
     * 删除成功
     */
    204: void;
};

export type DeleteTagResponse = DeleteTagResponses[keyof DeleteTagResponses];

export type UpdateTagData = {
    body: TagCreateRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/tags/{id}';
};

export type UpdateTagErrors = {
    /**
     * 未认证或 token 失效
     */
    401: ApiResponse;
    /**
     * 资源不存在或无权访问
     */
    404: ApiResponse;
    /**
     * 资源冲突（用户名/邮箱/分类名/标签名重复）
     */
    409: ApiResponse;
};

export type UpdateTagError = UpdateTagErrors[keyof UpdateTagErrors];

export type UpdateTagResponses = {
    /**
     * 更新成功
     */
    200: TagResponse;
};

export type UpdateTagResponse = UpdateTagResponses[keyof UpdateTagResponses];

export type SubscribeNotificationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/sse/notifications';
};

export type SubscribeNotificationsErrors = {
    /**
     * 未认证或 token 失效
     */
    401: ApiResponse;
};

export type SubscribeNotificationsError = SubscribeNotificationsErrors[keyof SubscribeNotificationsErrors];

export type SubscribeNotificationsResponses = {
    /**
     * SSE 流建立成功
     */
    200: string;
};

export type SubscribeNotificationsResponse = SubscribeNotificationsResponses[keyof SubscribeNotificationsResponses];
