// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api/v1` | (string & {});
};

export type EventCreateRequest = {
    title: string;
    description?: string;
    startTime: string;
    endTime: string;
    allDay?: boolean;
    location?: string;
    color?: string;
    reminderMinutes?: number;
    categoryId?: number;
    tagIds?: Array<number>;
};

export type EventUpdateRequest = EventCreateRequest;

export type EventResponse = {
    id?: number;
    title?: string;
    description?: string;
    startTime?: string;
    endTime?: string;
    allDay?: boolean;
    location?: string;
    color?: string;
    reminderMinutes?: number;
    categoryId?: number;
    categoryName?: string;
    categoryColor?: string;
    tags?: Array<TagResponse>;
    createdAt?: string;
    updatedAt?: string;
};

export type EventListResponse = {
    code?: number;
    message?: string;
    data?: Array<EventResponse>;
};

export type CategoryCreateRequest = {
    name: string;
    color?: string;
    description?: string;
};

export type CategoryResponse = {
    id?: number;
    name?: string;
    color?: string;
    description?: string;
};

export type CategoryListResponse = {
    code?: number;
    message?: string;
    data?: Array<CategoryResponse>;
};

export type TagCreateRequest = {
    name: string;
    color?: string;
};

export type TagResponse = {
    id?: number;
    name?: string;
    color?: string;
};

export type TagListResponse = {
    code?: number;
    message?: string;
    data?: Array<TagResponse>;
};

export type ApiResponse = {
    code?: number;
    message?: string;
    data?: {
        [key: string]: unknown;
    };
};

export type ListEventsData = {
    body?: never;
    path?: never;
    query: {
        start: string;
        end: string;
        categoryId?: number;
    };
    url: '/events';
};

export type ListEventsResponses = {
    /**
     * 成功
     */
    200: EventListResponse;
};

export type ListEventsResponse = ListEventsResponses[keyof ListEventsResponses];

export type CreateEventData = {
    body: EventCreateRequest;
    path?: never;
    query?: never;
    url: '/events';
};

export type CreateEventResponses = {
    /**
     * 创建成功
     */
    201: EventResponse;
};

export type CreateEventResponse = CreateEventResponses[keyof CreateEventResponses];

export type DeleteEventData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/events/{id}';
};

export type DeleteEventResponses = {
    /**
     * 删除成功
     */
    204: void;
};

export type DeleteEventResponse = DeleteEventResponses[keyof DeleteEventResponses];

export type GetEventByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/events/{id}';
};

export type GetEventByIdResponses = {
    /**
     * 成功
     */
    200: EventResponse;
};

export type GetEventByIdResponse = GetEventByIdResponses[keyof GetEventByIdResponses];

export type UpdateEventData = {
    body: EventUpdateRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/events/{id}';
};

export type UpdateEventResponses = {
    /**
     * 更新成功
     */
    200: EventResponse;
};

export type UpdateEventResponse = UpdateEventResponses[keyof UpdateEventResponses];

export type ListCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/categories';
};

export type ListCategoriesResponses = {
    /**
     * 成功
     */
    200: CategoryListResponse;
};

export type ListCategoriesResponse = ListCategoriesResponses[keyof ListCategoriesResponses];

export type CreateCategoryData = {
    body: CategoryCreateRequest;
    path?: never;
    query?: never;
    url: '/categories';
};

export type CreateCategoryResponses = {
    /**
     * 创建成功
     */
    201: CategoryResponse;
};

export type CreateCategoryResponse = CreateCategoryResponses[keyof CreateCategoryResponses];

export type DeleteCategoryData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/categories/{id}';
};

export type DeleteCategoryResponses = {
    /**
     * 删除成功
     */
    204: void;
};

export type DeleteCategoryResponse = DeleteCategoryResponses[keyof DeleteCategoryResponses];

export type UpdateCategoryData = {
    body: CategoryCreateRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/categories/{id}';
};

export type UpdateCategoryResponses = {
    /**
     * 更新成功
     */
    200: unknown;
};

export type ListTagsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tags';
};

export type ListTagsResponses = {
    /**
     * 成功
     */
    200: TagListResponse;
};

export type ListTagsResponse = ListTagsResponses[keyof ListTagsResponses];

export type CreateTagData = {
    body: TagCreateRequest;
    path?: never;
    query?: never;
    url: '/tags';
};

export type CreateTagResponses = {
    /**
     * 创建成功
     */
    201: unknown;
};

export type DeleteTagData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/tags/{id}';
};

export type DeleteTagResponses = {
    /**
     * 删除成功
     */
    204: void;
};

export type DeleteTagResponse = DeleteTagResponses[keyof DeleteTagResponses];

export type UpdateTagData = {
    body: TagCreateRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/tags/{id}';
};

export type UpdateTagResponses = {
    /**
     * 更新成功
     */
    200: unknown;
};
